"""add_user_auth_fields

Revision ID: 162305e435a3
Revises: 26a38178e52d
Create Date: 2026-07-19 13:29:16.505474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162305e435a3'
down_revision: Union[str, None] = '26a38178e52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=32), server_default='user', nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=32), server_default='local', nullable=False))
    op.add_column('users', sa.Column('oauth_subject', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_unique_constraint('uq_users_auth_provider_oauth_subject', 'users', ['auth_provider', 'oauth_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_auth_provider_oauth_subject', 'users', type_='unique')
    op.drop_index('ix_users_role', table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
