"""create_core_tables

Revision ID: 26a38178e52d
Revises: 
Create Date: 2026-07-19 13:26:05.432581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26a38178e52d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emotions_slug', 'emotions', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('verses',
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('sanskrit', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('translation_source', sa.String(length=120), nullable=True),
    sa.Column('commentary', sa.Text(), nullable=True),
    sa.Column('qdrant_point_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter', 'verse_number', name='uq_verses_chapter_verse_number')
    )
    op.create_index('ix_verses_chapter', 'verses', ['chapter'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_id_created_at', 'conversations', ['user_id', 'created_at'], unique=False)
    op.create_table('journals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood_note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journals_user_id_created_at', 'journals', ['user_id', 'created_at'], unique=False)
    op.create_table('journal_emotions',
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('emotion_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('journal_id', 'emotion_id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_role', 'messages', ['role'], unique=False)
    op.create_table('reflections',
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verse_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reflections_journal_id_created_at', 'reflections', ['journal_id', 'created_at'], unique=False)
    op.create_index('ix_reflections_user_id_created_at', 'reflections', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_reflections_verse_id', 'reflections', ['verse_id'], unique=False)
    op.create_table('feedback',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_feedback_user_message')
    )
    op.create_index('ix_feedback_message_id', 'feedback', ['message_id'], unique=False)
    op.create_index('ix_feedback_user_id_created_at', 'feedback', ['user_id', 'created_at'], unique=False)
    op.create_table('message_emotions',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('emotion_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'emotion_id')
    )
    op.create_table('message_verses',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('verse_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('message_id', 'verse_id')
    )
    op.create_table('prompt_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('completion', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='success', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_logs_conversation_id_created_at', 'prompt_logs', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_prompt_logs_message_id', 'prompt_logs', ['message_id'], unique=False)
    op.create_index('ix_prompt_logs_status', 'prompt_logs', ['status'], unique=False)
    op.create_index('ix_prompt_logs_user_id_created_at', 'prompt_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_logs_user_id_created_at', table_name='prompt_logs')
    op.drop_index('ix_prompt_logs_status', table_name='prompt_logs')
    op.drop_index('ix_prompt_logs_message_id', table_name='prompt_logs')
    op.drop_index('ix_prompt_logs_conversation_id_created_at', table_name='prompt_logs')
    op.drop_table('prompt_logs')
    op.drop_table('message_verses')
    op.drop_table('message_emotions')
    op.drop_index('ix_feedback_user_id_created_at', table_name='feedback')
    op.drop_index('ix_feedback_message_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_reflections_verse_id', table_name='reflections')
    op.drop_index('ix_reflections_user_id_created_at', table_name='reflections')
    op.drop_index('ix_reflections_journal_id_created_at', table_name='reflections')
    op.drop_table('reflections')
    op.drop_index('ix_messages_role', table_name='messages')
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('journal_emotions')
    op.drop_index('ix_journals_user_id_created_at', table_name='journals')
    op.drop_table('journals')
    op.drop_index('ix_conversations_user_id_created_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_verses_chapter', table_name='verses')
    op.drop_table('verses')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_emotions_slug', table_name='emotions')
    op.drop_table('emotions')
    # ### end Alembic commands ###
