"""add_verse_topics_emotions

Revision ID: 8c6e0d6c9f3c
Revises: 162305e435a3
Create Date: 2026-07-19 13:37:57.740481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6e0d6c9f3c'
down_revision: Union[str, None] = '162305e435a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verses', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('verses', sa.Column('emotions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.create_index('ix_verses_emotions', 'verses', ['emotions'], unique=False, postgresql_using='gin')
    op.create_index('ix_verses_topics', 'verses', ['topics'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verses_topics', table_name='verses', postgresql_using='gin')
    op.drop_index('ix_verses_emotions', table_name='verses', postgresql_using='gin')
    op.drop_column('verses', 'emotions')
    op.drop_column('verses', 'topics')
    # ### end Alembic commands ###
